# -*- mode: ruby -*-
# vi: set ft=ruby :

# Rapid Translation Toolkitor Development Environment
# Copyright (C) 2015  Wycliffe Bible Translators

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.name = "mgiza"
    v.cpus = 1
  end
  config.vm.synced_folder "tools/", "/home/vagrant/tools"
  config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
    s.args = ["/home/vagrant","vagrant"]
  end
end