# -*- mode: ruby -*-
# vi: set ft=ruby :

# Enhanced Rapid Word Collection Development Environment
# Copyright (C) 2015  Wycliffe Bible Translators

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.name = "mgiza"
    v.cpus = 1
  end
  config.vm.provision "shell", inline: "mkdir /home/vagrant/tools && chown vagrant:vagrant /home/vagrant/tools"
  config.vm.provision "file", source: "getcorpora.sh", destination: "/home/vagrant/tools/getcorpora.sh"
  config.vm.provision "file", source: "tokenize.sh", destination: "/home/vagrant/tools/tokenize.sh"
  config.vm.provision "file", source: "mgiza_configfile", destination: "/home/vagrant/tools/mgiza_configfile"
  config.vm.provision "shell", path: "bootstrap.sh"
end