forge "http://forge.puppetlabs.com"

mod "puppetlabs-stdlib"
mod "puppetlabs-concat"
mod "puppetlabs-nodejs"
mod "jfryman-nginx"
mod "camptocamp-couchdb",
    :git => 'https://github.com/bbriggs/puppet-couchdb.git',
    :ref => 'development'
